--번호, 작성자, 제목, 내용, 작성일
CREATE TABLE MDBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(500) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	REGDATE DATE NOT NULL
);

CREATE SEQUENCE MDBOARDSEQ;

INSERT INTO MDBOARD
VALUES(MDBOARDSEQ.NEXTVAL, '관리자', 'TEST', 'TEST123456789', SYSDATE);

SELECT * FROM MDBOARD;